/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head';
import Container from '@material-ui/core/Container';
import Header from './Header';
import Footer from './Footer';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>escapedmonks</title>
				<meta name='description' content='Generated by create next app' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
				/>
				<link rel='icon' href='/assets/logo.png' />
			</Head>
			<Container fixed className={styles.container}>
				<Header />
				<Footer />
			</Container>
		</>
	);
}
