/* eslint-disable @next/next/no-page-custom-font */
import React, { useState, useLayoutEffect } from 'react';
import Box from '@material-ui/core/Box';
import Head from 'next/head';
import Header from './Header';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';
import TouristSpots from '../pages/Views/TouristSpots';
import About from '../pages/Views/About';
import Quote from '../components/RandomQuote';
import CoolStep from '../components/CoolStepper';

export default function Home() {
	const [showFooter, setFooter] = useState(false);

	useLayoutEffect(() => {
		setFooter(true);
	}, []);
	return (
		<>
			<Head>
				<title>escapedmonks</title>
				<meta name='description' content='Generated by create next app' />
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
				/>
				<link rel='icon' href='/assets/logo.png' />
			</Head>
			<div className={styles.container}>
				<Header />
				<About />
				{showFooter && <Quote />}
				<TouristSpots />
				{showFooter && <CoolStep />}
				{showFooter && <Footer />}
			</div>
		</>
	);
}
